/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Harami_room_mates;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ayshi
 */
public class Calculation extends javax.swing.JFrame {

    public boolean flag;
    /**
     * Creates new form Calculation
     */
    public Calculation() {
        initComponents();
    }
     public Calculation(String pere) {
        initComponents();
        Month.setText(pere);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenu1 = new javax.swing.JMenu();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Ayshik = new javax.swing.JLabel();
        D1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        M1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        B1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        F1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Saad = new javax.swing.JLabel();
        D2 = new javax.swing.JTextField();
        M2 = new javax.swing.JTextField();
        B2 = new javax.swing.JLabel();
        F2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Sinam = new javax.swing.JLabel();
        D3 = new javax.swing.JTextField();
        M3 = new javax.swing.JTextField();
        B3 = new javax.swing.JLabel();
        F3 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        Sifat = new javax.swing.JLabel();
        D4 = new javax.swing.JTextField();
        M4 = new javax.swing.JTextField();
        B4 = new javax.swing.JLabel();
        F4 = new javax.swing.JLabel();
        Shuvo = new javax.swing.JLabel();
        D5 = new javax.swing.JTextField();
        M5 = new javax.swing.JTextField();
        B5 = new javax.swing.JLabel();
        F5 = new javax.swing.JLabel();
        Swapnil = new javax.swing.JLabel();
        D6 = new javax.swing.JTextField();
        M6 = new javax.swing.JTextField();
        B6 = new javax.swing.JLabel();
        F6 = new javax.swing.JLabel();
        Rakib = new javax.swing.JLabel();
        D7 = new javax.swing.JTextField();
        M7 = new javax.swing.JTextField();
        B7 = new javax.swing.JLabel();
        F7 = new javax.swing.JLabel();
        Rafi = new javax.swing.JLabel();
        D8 = new javax.swing.JTextField();
        M8 = new javax.swing.JTextField();
        B8 = new javax.swing.JLabel();
        F8 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        TD = new javax.swing.JLabel();
        TM = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        TB = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        MR = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        MV2 = new javax.swing.JTextField();
        MV3 = new javax.swing.JTextField();
        MV4 = new javax.swing.JTextField();
        MV5 = new javax.swing.JTextField();
        MV6 = new javax.swing.JTextField();
        TM1 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        Meal_taka = new javax.swing.JTextField();
        TM2 = new javax.swing.JLabel();
        Dibe = new javax.swing.JLabel();
        SV2 = new javax.swing.JTextField();
        SV3 = new javax.swing.JTextField();
        SV4 = new javax.swing.JTextField();
        SV5 = new javax.swing.JTextField();
        SV6 = new javax.swing.JTextField();
        SV8 = new javax.swing.JTextField();
        SV7 = new javax.swing.JTextField();
        MV1 = new javax.swing.JTextField();
        SV1 = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        TM3 = new javax.swing.JLabel();
        Pabe = new javax.swing.JLabel();
        GHAPLA = new javax.swing.JLabel();
        TM4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        GHAPLA1 = new javax.swing.JLabel();
        Month = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Total Meal");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("dd");

        jMenu1.setText("jMenu1");

        jButton4.setBackground(new java.awt.Color(255, 204, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 0, 0));
        jButton4.setText("MEAL RATE");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("Calculation");

        Ayshik.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Ayshik.setText("Ayshik");

        D1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        D1.setForeground(new java.awt.Color(255, 0, 51));
        D1.setText("0");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Deposited");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText(" Meal");

        M1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        M1.setForeground(new java.awt.Color(255, 0, 51));
        M1.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Balance");

        B1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B1.setForeground(new java.awt.Color(255, 255, 0));
        B1.setText("-----");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Final Result");

        F1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        F1.setForeground(new java.awt.Color(255, 0, 51));
        F1.setText("-----");

        jLabel11.setText("------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        Saad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Saad.setText("Saad");

        D2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        D2.setForeground(new java.awt.Color(255, 0, 51));
        D2.setText("0");

        M2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        M2.setForeground(new java.awt.Color(255, 0, 51));
        M2.setText("0");

        B2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B2.setForeground(new java.awt.Color(255, 255, 0));
        B2.setText("-----");

        F2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        F2.setForeground(new java.awt.Color(255, 0, 51));
        F2.setText("-----");

        jLabel15.setText("------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        Sinam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sinam.setText("Sinam");

        D3.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        D3.setForeground(new java.awt.Color(255, 0, 51));
        D3.setText("0");

        M3.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        M3.setForeground(new java.awt.Color(255, 0, 51));
        M3.setText("0");

        B3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B3.setForeground(new java.awt.Color(255, 255, 0));
        B3.setText("-----");

        F3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        F3.setForeground(new java.awt.Color(255, 0, 51));
        F3.setText("-----");

        jLabel32.setText("-------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        Sifat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sifat.setText("Sifat");

        D4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        D4.setForeground(new java.awt.Color(255, 0, 51));
        D4.setText("0");

        M4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        M4.setForeground(new java.awt.Color(255, 0, 51));
        M4.setText("0");

        B4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B4.setForeground(new java.awt.Color(255, 255, 0));
        B4.setText("-----");

        F4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        F4.setForeground(new java.awt.Color(255, 0, 51));
        F4.setText("-----");

        Shuvo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Shuvo.setText("Shuvo");

        D5.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        D5.setForeground(new java.awt.Color(255, 0, 51));
        D5.setText("0");

        M5.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        M5.setForeground(new java.awt.Color(255, 0, 51));
        M5.setText("0");

        B5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B5.setForeground(new java.awt.Color(255, 255, 0));
        B5.setText("-----");

        F5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        F5.setForeground(new java.awt.Color(255, 0, 51));
        F5.setText("-----");

        Swapnil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Swapnil.setText("Swapnil");

        D6.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        D6.setForeground(new java.awt.Color(255, 0, 51));
        D6.setText("0");

        M6.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        M6.setForeground(new java.awt.Color(255, 0, 51));
        M6.setText("0");

        B6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B6.setForeground(new java.awt.Color(255, 255, 0));
        B6.setText("-----");

        F6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        F6.setForeground(new java.awt.Color(255, 0, 51));
        F6.setText("-----");

        Rakib.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Rakib.setText("Rakib");

        D7.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        D7.setForeground(new java.awt.Color(255, 0, 51));
        D7.setText("0");

        M7.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        M7.setForeground(new java.awt.Color(255, 0, 51));
        M7.setText("0");

        B7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B7.setForeground(new java.awt.Color(255, 255, 0));
        B7.setText("-----");

        F7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        F7.setForeground(new java.awt.Color(255, 0, 51));
        F7.setText("-----");

        Rafi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Rafi.setText("Rafi");

        D8.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        D8.setForeground(new java.awt.Color(255, 0, 51));
        D8.setText("0");

        M8.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        M8.setForeground(new java.awt.Color(255, 0, 51));
        M8.setText("0");

        B8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B8.setForeground(new java.awt.Color(255, 255, 0));
        B8.setText("-----");

        F8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        F8.setForeground(new java.awt.Color(255, 0, 51));
        F8.setText("-----");

        jLabel48.setText("-------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel49.setText("-------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel50.setText("-------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel51.setText("-------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel52.setText("-------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel53.setText("Total DEposited--");

        TD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TD.setForeground(new java.awt.Color(255, 255, 0));
        TD.setText("----");

        TM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TM.setForeground(new java.awt.Color(255, 255, 0));
        TM.setText("---");

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel56.setText("Total Meal--");

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel57.setText("Total Bazar--");

        TB.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        TB.setForeground(new java.awt.Color(255, 0, 51));
        TB.setText("0");

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel58.setText("Meal Rate--");

        MR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MR.setForeground(new java.awt.Color(255, 0, 51));
        MR.setText("----");

        jLabel60.setText("------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        jButton1.setBackground(new java.awt.Color(255, 204, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("MEAL RATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel54.setBackground(new java.awt.Color(255, 51, 255));
        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 0, 0));
        jLabel54.setText("Manager's Ghapla");

        MV2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        MV2.setForeground(new java.awt.Color(255, 0, 51));
        MV2.setText("0");
        MV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MV2ActionPerformed(evt);
            }
        });

        MV3.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        MV3.setForeground(new java.awt.Color(255, 0, 51));
        MV3.setText("0");

        MV4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        MV4.setForeground(new java.awt.Color(255, 0, 51));
        MV4.setText("0");

        MV5.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        MV5.setForeground(new java.awt.Color(255, 0, 51));
        MV5.setText("0");

        MV6.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        MV6.setForeground(new java.awt.Color(255, 0, 51));
        MV6.setText("0");

        TM1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TM1.setForeground(new java.awt.Color(0, 153, 0));
        TM1.setText("+");

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel59.setText("Meal TK");

        Meal_taka.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        Meal_taka.setForeground(new java.awt.Color(255, 0, 51));
        Meal_taka.setText("0");

        TM2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TM2.setForeground(new java.awt.Color(0, 153, 0));
        TM2.setText("=");

        Dibe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Dibe.setForeground(new java.awt.Color(255, 0, 51));
        Dibe.setText("----");

        SV2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        SV2.setForeground(new java.awt.Color(255, 0, 51));
        SV2.setText("0");

        SV3.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        SV3.setForeground(new java.awt.Color(255, 0, 51));
        SV3.setText("0");

        SV4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        SV4.setForeground(new java.awt.Color(255, 0, 51));
        SV4.setText("0");

        SV5.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        SV5.setForeground(new java.awt.Color(255, 0, 51));
        SV5.setText("0");

        SV6.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        SV6.setForeground(new java.awt.Color(255, 0, 51));
        SV6.setText("0");

        SV8.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        SV8.setForeground(new java.awt.Color(255, 0, 51));
        SV8.setText("0");

        SV7.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        SV7.setForeground(new java.awt.Color(255, 0, 51));
        SV7.setText("0");

        MV1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        MV1.setForeground(new java.awt.Color(255, 0, 51));
        MV1.setText("0");

        SV1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        SV1.setForeground(new java.awt.Color(255, 0, 51));
        SV1.setText("0");

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(204, 51, 0));
        jLabel61.setText("(-) Values-");

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(204, 51, 0));
        jLabel62.setText("(+) Values-");

        TM3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TM3.setForeground(new java.awt.Color(0, 153, 0));
        TM3.setText("=");

        Pabe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Pabe.setForeground(new java.awt.Color(255, 0, 51));
        Pabe.setText("----");

        GHAPLA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        GHAPLA.setForeground(new java.awt.Color(255, 255, 255));
        GHAPLA.setText("--------");

        TM4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TM4.setForeground(new java.awt.Color(0, 153, 0));
        TM4.setText("=");

        jButton2.setBackground(new java.awt.Color(255, 204, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("VIEW GHAPLA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        GHAPLA1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        GHAPLA1.setText("[----------------------------------------------------------------]");

        Month.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Month.setText("-----------");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Harami_room_mates/iconfinder_Button_Back_72907.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 204, 153));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(204, 0, 0));
        jButton6.setText("Save All");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 204, 153));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(204, 0, 0));
        jButton7.setText("View All");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(Ayshik)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(D1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(M1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(F1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton3)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Shuvo)
                                        .addGap(45, 45, 45)
                                        .addComponent(D5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(M5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Sifat)
                                        .addGap(57, 57, 57)
                                        .addComponent(D4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62)
                                        .addComponent(M4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(F5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(F4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel52, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel51, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Saad)
                                .addGap(51, 51, 51)
                                .addComponent(D2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(M2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(F2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Swapnil)
                                .addGap(35, 35, 35)
                                .addComponent(D6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(M6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(F6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Rakib)
                                .addGap(51, 51, 51)
                                .addComponent(D7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(M7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(F7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Rafi)
                                .addGap(61, 61, 61)
                                .addComponent(D8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(M8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(F8, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Sinam)
                                        .addGap(44, 44, 44)
                                        .addComponent(D3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(M3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(F3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel53)
                                .addGap(41, 41, 41)
                                .addComponent(TD, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel56)
                                .addGap(86, 86, 86)
                                .addComponent(TM, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(269, 269, 269)
                                .addComponent(jLabel57)
                                .addGap(34, 34, 34)
                                .addComponent(TB, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel58)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel62)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SV1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MV1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel54))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TM4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GHAPLA, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(GHAPLA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(MV2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MV3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MV4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MV5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MV6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TM1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel59)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Meal_taka, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TM2)
                                        .addGap(14, 14, 14)
                                        .addComponent(Dibe, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(SV2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SV3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SV4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SV5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SV6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SV7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SV8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TM3)
                                        .addGap(18, 18, 18)
                                        .addComponent(Pabe, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(Month))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jButton6)
                                .addComponent(jButton7)))))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(19, 19, 19)
                .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ayshik)
                    .addComponent(M1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Saad)
                    .addComponent(M2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sinam)
                    .addComponent(M3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sifat)
                    .addComponent(M4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Shuvo)
                    .addComponent(M5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Swapnil)
                    .addComponent(M6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rakib)
                    .addComponent(M7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rafi)
                    .addComponent(M8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(TD, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TM, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel56)
                    .addComponent(jLabel58)
                    .addComponent(MR, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MV4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MV5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MV6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TM1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel59)
                    .addComponent(Meal_taka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TM2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel61)
                    .addComponent(Dibe, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SV4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SV5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SV6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SV8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SV7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel62)
                    .addComponent(TM3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pabe))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(GHAPLA, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TM4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GHAPLA1))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        {   int one=Integer.parseInt(MV1.getText());
            int two=Integer.parseInt(MV2.getText());
            int three=Integer.parseInt(MV3.getText());
            int four=Integer.parseInt(MV4.getText());
            int five=Integer.parseInt(MV5.getText());
            int six=Integer.parseInt(MV6.getText());
            int meal_taka=Integer.parseInt(Meal_taka.getText());
            String ans=String.valueOf(-one-two-three-four-five-six-meal_taka);
            Dibe.setText(ans);}

        {
            int one=Integer.parseInt(SV1.getText());
            int two=Integer.parseInt(SV2.getText());
            int three=Integer.parseInt(SV3.getText());
            int four=Integer.parseInt(SV4.getText());
            int five=Integer.parseInt(SV5.getText());
            int six=Integer.parseInt(SV6.getText());
            int seven=Integer.parseInt(SV7.getText());
            int eight=Integer.parseInt(SV8.getText());
            String ans=String.valueOf(one+two+three+four+five+six+seven+eight);
            Pabe.setText(ans);
        }

        {  int de=Integer.parseInt(Dibe.getText());
            int pa=Integer.parseInt(Pabe.getText());

            String ans=String.valueOf(pa+de);
            GHAPLA.setText(ans);
        }
        {
             int gap=Integer.parseInt(GHAPLA.getText());
            if(gap<=20){
            GHAPLA1.setText("Congratulation you are an HONEST manager!!");
            
            
            }
            else{
            
            GHAPLA1.setText("Manager ke sap diya chod!!!");
            
            
            }
            
           
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void MV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MV2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        { int one=Integer.parseInt(D1.getText());
            int two=Integer.parseInt(D2.getText());
            int three=Integer.parseInt(D3.getText());
            int four=Integer.parseInt(D4.getText());
            int five=Integer.parseInt(D5.getText());
            int six=Integer.parseInt(D6.getText());
            int seven=Integer.parseInt(D7.getText());
            int eight=Integer.parseInt(D8.getText());
            String ans=String.valueOf(one+two+three+four+five+six+seven+eight);
            TD.setText(ans);}
        {int one=Integer.parseInt(M1.getText());
            int two=Integer.parseInt(M2.getText());
            int three=Integer.parseInt(M3.getText());
            int four=Integer.parseInt(M4.getText());
            int five=Integer.parseInt(M5.getText());
            int six=Integer.parseInt(M6.getText());
            int seven=Integer.parseInt(M7.getText());
            int eight=Integer.parseInt(M8.getText());
            String ans=String.valueOf(one+two+three+four+five+six+seven+eight);
            TM.setText(ans);
        }

        { double total_Bazar=Double.valueOf(TB.getText());
            double total_Meal=Double.valueOf(TM.getText());
            double Meal_Rate=(total_Bazar/total_Meal);
            MR.setText(""+Meal_Rate);
        }

        {
            int one=Integer.parseInt(M1.getText());
            int two=Integer.parseInt(M2.getText());
            int three=Integer.parseInt(M3.getText());
            int four=Integer.parseInt(M4.getText());
            int five=Integer.parseInt(M5.getText());
            int six=Integer.parseInt(M6.getText());
            int seven=Integer.parseInt(M7.getText());
            int eight=Integer.parseInt(M8.getText());
            double meal_Rate=Double.valueOf(MR.getText());
            double Bans1=(meal_Rate*one);
            double Bans2=(meal_Rate*two);
            double Bans3=(meal_Rate*three);
            double Bans4=(meal_Rate*four);
            double Bans5=(meal_Rate*five);
            double Bans6=(meal_Rate*six);
            double Bans7=(meal_Rate*seven);
            double Bans8=(meal_Rate*eight);
            B1.setText(""+Bans1);
            B2.setText(""+Bans2);
            B3.setText(""+Bans3);
            B4.setText(""+Bans4);
            B5.setText(""+Bans5);
            B6.setText(""+Bans6);
            B7.setText(""+Bans7);
            B8.setText(""+Bans8);
        }

        {
            int one=Integer.parseInt(D1.getText());
            int two=Integer.parseInt(D2.getText());
            int three=Integer.parseInt(D3.getText());
            int four=Integer.parseInt(D4.getText());
            int five=Integer.parseInt(D5.getText());
            int six=Integer.parseInt(D6.getText());
            int seven=Integer.parseInt(D7.getText());
            int eight=Integer.parseInt(D8.getText());
            double Bone1=Double.valueOf(B1.getText());
            double Bone2=Double.valueOf(B2.getText());
            double Bone3=Double.valueOf(B3.getText());
            double Bone4=Double.valueOf(B4.getText());
            double Bone5=Double.valueOf(B5.getText());
            double Bone6=Double.valueOf(B6.getText());
            double Bone7=Double.valueOf(B7.getText());
            double Bone8=Double.valueOf(B8.getText());
            double Final_result1=(one-Bone1);
            double Final_result2=(two-Bone2);
            double Final_result3=(three-Bone3);
            double Final_result4=(four-Bone4);
            double Final_result5=(five-Bone5);
            double Final_result6=(six-Bone6);
            double Final_result7=(seven-Bone7);
            double Final_result8=(eight-Bone8);
            F1.setText(""+Final_result1);
            F2.setText(""+Final_result2);
            F3.setText(""+Final_result3);
            F4.setText(""+Final_result4);
            F5.setText(""+Final_result5);
            F6.setText(""+Final_result6);
            F7.setText(""+Final_result7);
            F8.setText(""+Final_result8);
        }
        { 
          double Meal_rate=Double.parseDouble(MR.getText());
            if(Meal_rate<=35.00){
            GHAPLA1.setText("OHHHH YAAAHHH YOU ARE A GOOD MANAGER!!");
            
            
            }
            else{
            
            GHAPLA1.setText("SAUAA CHUDI VODAR MANAGER!!!");
            
            
            }
        
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
TableCreateForm tcf=new TableCreateForm();
tcf.setVisible(true);
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 EntryIntoDB();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
DataShow();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ayshik;
    private javax.swing.JLabel B1;
    private javax.swing.JLabel B2;
    private javax.swing.JLabel B3;
    private javax.swing.JLabel B4;
    private javax.swing.JLabel B5;
    private javax.swing.JLabel B6;
    private javax.swing.JLabel B7;
    private javax.swing.JLabel B8;
    private javax.swing.JTextField D1;
    private javax.swing.JTextField D2;
    private javax.swing.JTextField D3;
    private javax.swing.JTextField D4;
    private javax.swing.JTextField D5;
    private javax.swing.JTextField D6;
    private javax.swing.JTextField D7;
    private javax.swing.JTextField D8;
    private javax.swing.JLabel Dibe;
    private javax.swing.JLabel F1;
    private javax.swing.JLabel F2;
    private javax.swing.JLabel F3;
    private javax.swing.JLabel F4;
    private javax.swing.JLabel F5;
    private javax.swing.JLabel F6;
    private javax.swing.JLabel F7;
    private javax.swing.JLabel F8;
    private javax.swing.JLabel GHAPLA;
    private javax.swing.JLabel GHAPLA1;
    private javax.swing.JTextField M1;
    private javax.swing.JTextField M2;
    private javax.swing.JTextField M3;
    private javax.swing.JTextField M4;
    private javax.swing.JTextField M5;
    private javax.swing.JTextField M6;
    private javax.swing.JTextField M7;
    private javax.swing.JTextField M8;
    private javax.swing.JLabel MR;
    private javax.swing.JTextField MV1;
    private javax.swing.JTextField MV2;
    private javax.swing.JTextField MV3;
    private javax.swing.JTextField MV4;
    private javax.swing.JTextField MV5;
    private javax.swing.JTextField MV6;
    private javax.swing.JTextField Meal_taka;
    private javax.swing.JLabel Month;
    private javax.swing.JLabel Pabe;
    private javax.swing.JLabel Rafi;
    private javax.swing.JLabel Rakib;
    private javax.swing.JTextField SV1;
    private javax.swing.JTextField SV2;
    private javax.swing.JTextField SV3;
    private javax.swing.JTextField SV4;
    private javax.swing.JTextField SV5;
    private javax.swing.JTextField SV6;
    private javax.swing.JTextField SV7;
    private javax.swing.JTextField SV8;
    private javax.swing.JLabel Saad;
    private javax.swing.JLabel Shuvo;
    private javax.swing.JLabel Sifat;
    private javax.swing.JLabel Sinam;
    private javax.swing.JLabel Swapnil;
    private javax.swing.JTextField TB;
    private javax.swing.JLabel TD;
    private javax.swing.JLabel TM;
    private javax.swing.JLabel TM1;
    private javax.swing.JLabel TM2;
    private javax.swing.JLabel TM3;
    private javax.swing.JLabel TM4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables


public void EntryIntoDB()
        
	{
		String query = "UPDATE "+Month.getText()+" SET `Deposit`='"+D1.getText()+"', `Totalmeal`='"+M1.getText()+"', `MealRate`='"+MR.getText()+"', `TotalBazar`='"+TB.getText()+"',`RemainingM`='"+Meal_taka.getText()+"', `Balance`='"+B1.getText()+"', `Final_result`='"+F1.getText()+"', `MGhapla`='"+GHAPLA.getText()+"' WHERE `Name`='"+Ayshik.getText()+"'";
		String query1 = "UPDATE "+Month.getText()+" SET `Deposit`='"+D2.getText()+"', `Totalmeal`='"+M2.getText()+"', `MealRate`='"+MR.getText()+"', `TotalBazar`='"+TB.getText()+"',`RemainingM`='"+Meal_taka.getText()+"', `Balance`='"+B2.getText()+"', `Final_result`='"+F2.getText()+"', `MGhapla`='"+GHAPLA.getText()+"' WHERE `Name`='"+Saad.getText()+"'";
                String query2 = "UPDATE "+Month.getText()+" SET `Deposit`='"+D3.getText()+"', `Totalmeal`='"+M3.getText()+"', `MealRate`='"+MR.getText()+"', `TotalBazar`='"+TB.getText()+"',`RemainingM`='"+Meal_taka.getText()+"', `Balance`='"+B3.getText()+"', `Final_result`='"+F3.getText()+"', `MGhapla`='"+GHAPLA.getText()+"' WHERE `Name`='"+Sinam.getText()+"'";
                String query3 = "UPDATE "+Month.getText()+" SET `Deposit`='"+D4.getText()+"', `Totalmeal`='"+M4.getText()+"', `MealRate`='"+MR.getText()+"', `TotalBazar`='"+TB.getText()+"',`RemainingM`='"+Meal_taka.getText()+"', `Balance`='"+B4.getText()+"', `Final_result`='"+F4.getText()+"', `MGhapla`='"+GHAPLA.getText()+"' WHERE `Name`='"+Sifat.getText()+"'";
                String query4 = "UPDATE "+Month.getText()+" SET `Deposit`='"+D5.getText()+"', `Totalmeal`='"+M5.getText()+"', `MealRate`='"+MR.getText()+"', `TotalBazar`='"+TB.getText()+"',`RemainingM`='"+Meal_taka.getText()+"', `Balance`='"+B5.getText()+"', `Final_result`='"+F5.getText()+"', `MGhapla`='"+GHAPLA.getText()+"' WHERE `Name`='"+Shuvo.getText()+"'";
                String query5 = "UPDATE "+Month.getText()+" SET `Deposit`='"+D6.getText()+"', `Totalmeal`='"+M6.getText()+"', `MealRate`='"+MR.getText()+"', `TotalBazar`='"+TB.getText()+"',`RemainingM`='"+Meal_taka.getText()+"', `Balance`='"+B6.getText()+"', `Final_result`='"+F6.getText()+"', `MGhapla`='"+GHAPLA.getText()+"' WHERE `Name`='"+Swapnil.getText()+"'";
                String query6 = "UPDATE "+Month.getText()+" SET `Deposit`='"+D7.getText()+"', `Totalmeal`='"+M7.getText()+"', `MealRate`='"+MR.getText()+"', `TotalBazar`='"+TB.getText()+"',`RemainingM`='"+Meal_taka.getText()+"', `Balance`='"+B7.getText()+"', `Final_result`='"+F7.getText()+"', `MGhapla`='"+GHAPLA.getText()+"' WHERE `Name`='"+Rakib.getText()+"'";
                String query7 = "UPDATE "+Month.getText()+" SET `Deposit`='"+D8.getText()+"', `Totalmeal`='"+M8.getText()+"', `MealRate`='"+MR.getText()+"', `TotalBazar`='"+TB.getText()+"',`RemainingM`='"+Meal_taka.getText()+"', `Balance`='"+B8.getText()+"', `Final_result`='"+F8.getText()+"', `MGhapla`='"+GHAPLA.getText()+"' WHERE `Name`='"+Rafi.getText()+"'";
                
                System.out.println(query);
              
             
                
        try
		{
			Class.forName("com.mysql.cj.jdbc.Driver");
			Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/harami_room_mates", "root", "");
			Statement stm = con.createStatement();
			stm.execute(query);
                        stm.execute(query1);
                        stm.execute(query2);
                        stm.execute(query3);
                        stm.execute(query4);
                        stm.execute(query5);
                        stm.execute(query6);
                        stm.execute(query7);
                        
                        
                      
			stm.close();
			con.close();
                        JOptionPane.showMessageDialog(this,"CONGATULATIONS All Data HAS BEEN ADDED SUCCESSFULLY !!"); 
					
		}
        
        catch(Exception ex)
		{
			System.out.println("Exception : " +ex.getMessage());
        }
    }





public void DataShow()
	
{
        String query = "SELECT * FROM "+Month.getText()+"";
        
       
        Connection con=null;//connection er jonno
        java.sql.Statement st = null;//query execution korbe
		ResultSet rs = null;
                
                
                // ResultSet rs1 = null;// DB theke result collect korbe
		System.out.println(query);
        try
		{
			Class.forName("com.mysql.cj.jdbc.Driver");
			System.out.println("driver loaded");
			con = DriverManager.getConnection("jdbc:mysql://localhost:3306/harami_room_mates","root","");
			System.out.println("connection done");
			st = con.createStatement();
			System.out.println("statement created");
			rs = st.executeQuery(query);
                      
			System.out.println("results received");
			
			while(rs.next())
			{
              // jLabel7.setText(rs.getString("Card1No"));
               // jLabel8.setText(rs.getString("Card2No"));
                     		
                String name = rs.getString("Name");
               // String password2 = rs.getString("Card2Pin");
               
			//double balance = rs.getDouble("Balance");	
				
				
                    flag = false;
                    if(name.equals(Ayshik.getText()))
					{
						
                                                  D1.setText(rs.getString("Deposit"));
                                                  M1.setText(rs.getString("Totalmeal"));
                                                 
					}	
                    if(name.equals(Saad.getText()))
					{
						
                                                  D2.setText(rs.getString("Deposit"));
                                                  M2.setText(rs.getString("Totalmeal"));
                                                 
					}
                    if(name.equals(Sinam.getText()))
					{
						
                                                  D3.setText(rs.getString("Deposit"));
                                                  M3.setText(rs.getString("Totalmeal"));
                                                 
					}
                    
                    if(name.equals(Sifat.getText()))
					{
						
                                                  D4.setText(rs.getString("Deposit"));
                                                  M4.setText(rs.getString("Totalmeal"));
                                                 
					}
                    
                    
                    
                    
                    if(name.equals(Shuvo.getText()))
					{
						
                                                  D5.setText(rs.getString("Deposit"));
                                                  M5.setText(rs.getString("Totalmeal"));
                                                 
					}
                    
                    if(name.equals(Swapnil.getText()))
					{
						
                                                  D6.setText(rs.getString("Deposit"));
                                                  M6.setText(rs.getString("Totalmeal"));
                                                 
					}
                    
                    
                    
                    if(name.equals(Rakib.getText()))
					{
						
                                                  D7.setText(rs.getString("Deposit"));
                                                  M7.setText(rs.getString("Totalmeal"));
                                                 
					}
                    if(name.equals(Rafi.getText()))
					{
						
                                                  D8.setText(rs.getString("Deposit"));
                                                  M8.setText(rs.getString("Totalmeal"));
                                                   TB.setText(rs.getString("TotalBazar"));
                                                 
					}
                    
                    
                    
                    
                    
                    
                    
                        }
                      
			
		}
        catch(Exception ex)
		{
			System.out.println("Exception : " +ex.getMessage());
                        
        }
        finally
		{
            try
			{
                if(rs!=null)
					rs.close();

                if(st!=null)
					st.close();

                if(con!=null)
					con.close();
            }
            catch(Exception ex){}
        }
    } 



}
